### ISSUE TITLE
Error while finding module specification for 'paddlerec.run' (ModuleNotFoundError: No module named 'paddlerec')

### ISSUE THREAD

**Issue by ucasiggcas** [PaddlePaddle/PaddleRec#135]
hi,dear
没有这个东西啊，直接运行下面的
```
python -m paddlerec.run -m ./config.yaml
#or
python -m paddlerec.run -m paddlerec.models.recall.gnn
```
`Error while finding module specification for 'paddlerec.run' (ModuleNotFoundError: No module named 'paddlerec')`

咋解决啊，大佬

**Comment by ucasiggcas** [comment]
参考的是
Get start of PaddleRec in ten minutes
10分钟开始不了啊

**Comment by MrChengmo** [comment]
> 参考的是
> Get start of PaddleRec in ten minutes
> 10分钟开始不了啊

看起来是paddlerec没有被正确安装~

你的运行环境是什么？前述的paddlerec安装步骤有顺利完成吗？

如果是用源代码安装，安装成功后，应该会有下面的标志

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/29789135/86879329-6f13c380-c11d-11ea-93d3-76d5074dc85b.png">

**Comment by ucasiggcas** [comment]
hi，大佬，安装成功后执行gnn，得到如下结果正常吗？感觉有点不对啊
```
python -m paddlerec.run -m paddlerec.models.recall.gnn

batch: 1, LOSS: [10.669986], train_acc: [0.]
batch: 2, LOSS: [10.683549], train_acc: [0.]
batch: 3, LOSS: [10.669658], train_acc: [0.]
batch: 4, LOSS: [10.671809], train_acc: [0.]
batch: 5, LOSS: [10.660932], train_acc: [0.]
batch: 6, LOSS: [10.66907], train_acc: [0.]
batch: 7, LOSS: [10.665563], train_acc: [0.]
batch: 8, LOSS: [10.674797], train_acc: [0.]
batch: 9, LOSS: [10.670386], train_acc: [0.]
batch: 10, LOSS: [10.662183], train_acc: [0.1]
batch: 11, LOSS: [10.667716], train_acc: [0.]
batch: 12, LOSS: [10.666458], train_acc: [0.]
batch: 13, LOSS: [10.66883], train_acc: [0.]
batch: 14, LOSS: [10.671003], train_acc: [0.]
batch: 15, LOSS: [10.6745], train_acc: [0.]
batch: 16, LOSS: [10.669777], train_acc: [0.]
batch: 17, LOSS: [10.675078], train_acc: [0.]
batch: 18, LOSS: [10.672194], train_acc: [0.]
batch: 19, LOSS: [10.670609], train_acc: [0.]
epoch 0 done, use time: 1.2693278789520264
batch: 1, LOSS: [10.416034], train_acc: [0.3]
batch: 2, LOSS: [10.377094], train_acc: [0.3]
batch: 3, LOSS: [10.380407], train_acc: [0.3]
batch: 4, LOSS: [10.326581], train_acc: [0.4]
batch: 5, LOSS: [10.391391], train_acc: [0.2]
batch: 6, LOSS: [10.374437], train_acc: [0.3]
batch: 7, LOSS: [10.369722], train_acc: [0.1]
batch: 8, LOSS: [10.341339], train_acc: [0.2]
batch: 9, LOSS: [10.202948], train_acc: [0.2]
batch: 10, LOSS: [10.351052], train_acc: [0.3]
batch: 11, LOSS: [10.318689], train_acc: [0.1]
batch: 12, LOSS: [10.254948], train_acc: [0.1]
batch: 13, LOSS: [10.40401], train_acc: [0.4]
batch: 14, LOSS: [10.613649], train_acc: [0.3]
batch: 15, LOSS: [10.598577], train_acc: [0.1]
batch: 16, LOSS: [10.588185], train_acc: [0.2]
batch: 17, LOSS: [10.5907], train_acc: [0.1]
batch: 18, LOSS: [10.577959], train_acc: [0.2]
batch: 19, LOSS: [10.562983], train_acc: [0.]
epoch 1 done, use time: 1.245844841003418
PaddleRec Finish

```

**Comment by MrChengmo** [comment]
> hi，大佬，安装成功后执行gnn，得到如下结果正常吗？感觉有点不对啊
> 
> ```
> python -m paddlerec.run -m paddlerec.models.recall.gnn
> 
> batch: 1, LOSS: [10.669986], train_acc: [0.]
> batch: 2, LOSS: [10.683549], train_acc: [0.]
> batch: 3, LOSS: [10.669658], train_acc: [0.]
> batch: 4, LOSS: [10.671809], train_acc: [0.]
> batch: 5, LOSS: [10.660932], train_acc: [0.]
> batch: 6, LOSS: [10.66907], train_acc: [0.]
> batch: 7, LOSS: [10.665563], train_acc: [0.]
> batch: 8, LOSS: [10.674797], train_acc: [0.]
> batch: 9, LOSS: [10.670386], train_acc: [0.]
> batch: 10, LOSS: [10.662183], train_acc: [0.1]
> batch: 11, LOSS: [10.667716], train_acc: [0.]
> batch: 12, LOSS: [10.666458], train_acc: [0.]
> batch: 13, LOSS: [10.66883], train_acc: [0.]
> batch: 14, LOSS: [10.671003], train_acc: [0.]
> batch: 15, LOSS: [10.6745], train_acc: [0.]
> batch: 16, LOSS: [10.669777], train_acc: [0.]
> batch: 17, LOSS: [10.675078], train_acc: [0.]
> batch: 18, LOSS: [10.672194], train_acc: [0.]
> batch: 19, LOSS: [10.670609], train_acc: [0.]
> epoch 0 done, use time: 1.2693278789520264
> batch: 1, LOSS: [10.416034], train_acc: [0.3]
> batch: 2, LOSS: [10.377094], train_acc: [0.3]
> batch: 3, LOSS: [10.380407], train_acc: [0.3]
> batch: 4, LOSS: [10.326581], train_acc: [0.4]
> batch: 5, LOSS: [10.391391], train_acc: [0.2]
> batch: 6, LOSS: [10.374437], train_acc: [0.3]
> batch: 7, LOSS: [10.369722], train_acc: [0.1]
> batch: 8, LOSS: [10.341339], train_acc: [0.2]
> batch: 9, LOSS: [10.202948], train_acc: [0.2]
> batch: 10, LOSS: [10.351052], train_acc: [0.3]
> batch: 11, LOSS: [10.318689], train_acc: [0.1]
> batch: 12, LOSS: [10.254948], train_acc: [0.1]
> batch: 13, LOSS: [10.40401], train_acc: [0.4]
> batch: 14, LOSS: [10.613649], train_acc: [0.3]
> batch: 15, LOSS: [10.598577], train_acc: [0.1]
> batch: 16, LOSS: [10.588185], train_acc: [0.2]
> batch: 17, LOSS: [10.5907], train_acc: [0.1]
> batch: 18, LOSS: [10.577959], train_acc: [0.2]
> batch: 19, LOSS: [10.562983], train_acc: [0.]
> epoch 1 done, use time: 1.245844841003418
> PaddleRec Finish
> ```

这个是正常的，为了让用户简单跑起来，内置的是只有几十行的fake数据，所以loss和acc是不可参考的，替换成你的真实数据集跑下就可以了。

**Comment by ucasiggcas** [comment]
大佬，那么问题来了
咋改成gnn的train.txt数据集啊？
如下格式
```
1	1
2,3,4	4
2,3	4
2	3
5	6
7	8
9,10	11
9	10
12,13,14,14,15,16	17
12,13,14,14,15	16
12,13,14,14	15
12,13,14	14
12,13	14
12	13
18,18	19
18	18
20	21
5	22
23,24	25
23	24
26,11,10,27,28,29	30
26,11,10,27,28	29
26,11,10,27	28
26,11,10	27
26,11	10
26	11
31,32	33
31	32
34	35
36,37,38,39,40,37	41
36,37,38,39,40	37
36,37,38,39	40
36,37,38	39
36,37	38
36	37
42	43
44	45
46	47
48,49,48,50,51,22	51
48,49,48,50,51	22
48,49,48,50	51
48,49,48	50
48,49	48
48	49
52,52	53
52	52
54,55	56
54	55
57	57
58,59	58
58	59
60,61,61,62,63,62,64,65,62,66,67,68	68
60,61,61,62,63,62,64,65,62,66,67	68
60,61,61,62,63,62,64,65,62,66	67
60,61,61,62,63,62,64,65,62	66
60,61,61,62,63,62,64,65	62
```

**Comment by 123malin** [comment]
> 大佬，那么问题来了
> 咋改成gnn的train.txt数据集啊？
> 如下格式
> 
> ```
> 1	1
> 2,3,4	4
> 2,3	4
> 2	3
> 5	6
> 7	8
> 9,10	11
> 9	10
> 12,13,14,14,15,16	17
> 12,13,14,14,15	16
> 12,13,14,14	15
> 12,13,14	14
> 12,13	14
> 12	13
> 18,18	19
> 18	18
> 20	21
> 5	22
> 23,24	25
> 23	24
> 26,11,10,27,28,29	30
> 26,11,10,27,28	29
> 26,11,10,27	28
> 26,11,10	27
> 26,11	10
> 26	11
> 31,32	33
> 31	32
> 34	35
> 36,37,38,39,40,37	41
> 36,37,38,39,40	37
> 36,37,38,39	40
> 36,37,38	39
> 36,37	38
> 36	37
> 42	43
> 44	45
> 46	47
> 48,49,48,50,51,22	51
> 48,49,48,50,51	22
> 48,49,48,50	51
> 48,49,48	50
> 48,49	48
> 48	49
> 52,52	53
> 52	52
> 54,55	56
> 54	55
> 57	57
> 58,59	58
> 58	59
> 60,61,61,62,63,62,64,65,62,66,67,68	68
> 60,61,61,62,63,62,64,65,62,66,67	68
> 60,61,61,62,63,62,64,65,62,66	67
> 60,61,61,62,63,62,64,65,62	66
> 60,61,61,62,63,62,64,65	62
> ```

1. 在gnn目录下先执行sh data_prepare.sh准备真实数据
2. 修改config.yaml中的workspace的路径，换成当前gnn所在的目录，如下所示：
![image](https://user-images.githubusercontent.com/11266280/86886144-fc104a00-c128-11ea-9929-550d1d99450c.png)
3. 在当前目录执行python -m paddlerec.run -m ./config.yaml

**Comment by ucasiggcas** [comment]
@123malin 
大佬data_prepare.sh下载的数据如下示例：
```
session_id;user_id;item_id;timeframe;eventdate
1;NA;81766;526309;2016-05-09
1;NA;31331;1031018;2016-05-09
1;NA;32118;243569;2016-05-09
1;NA;9654;75848;2016-05-09
1;NA;32627;1112408;2016-05-09
1;NA;33043;173912;2016-05-09
1;NA;12352;329870;2016-05-09
1;NA;35077;390072;2016-05-09
1;NA;36118;487369;2016-05-09
1;NA;129055;991416;2016-05-09
2;NA;3147;883039;2016-05-09
2;NA;32754;359839;2016-05-09
2;NA;100747;38317;2016-05-09
2;NA;32971;182759;2016-05-09
2;NA;10657;387340;2016-05-09
2;NA;35606;756335;2016-05-09
2;NA;35606;53684;2016-05-09
2;NA;36246;332000;2016-05-09
2;NA;36246;722492;2016-05-09
2;NA;196110;1045018;2016-05-09
4;NA;13931;21812;2016-05-09
5;NA;5140;22430;2016-05-09
5;NA;35472;121036;2016-05-09
6;NA;73191;53123;2016-05-09
6;NA;382683;88337;2016-05-09
7;NA;59248;38806;2016-05-09
7;NA;59248;328086;2016-05-09
7;NA;9416;271202;2016-05-09
7;NA;40639;14808;2016-05-09
7;NA;40639;432980;2016-05-09
7;NA;40639;161072;2016-05-09
7;NA;73816;69100;2016-05-09
7;NA;32742;186920;2016-05-09
7;NA;79626;358743;2016-05-09
7;NA;388131;583388;2016-05-09
8;NA;11542;10067;2016-04-10
10;NA;69597;193275;2016-04-05
10;NA;5103;5639;2016-04-05
.....
295645;NA;32950;263151;2016-03-22
295645;NA;68708;381295;2016-03-22
295645;NA;7017;22863;2016-03-22
295646;117396;20717;371823;2016-03-17
295646;117396;15330;822956;2016-03-17
295646;117396;30605;342923;2016-03-17
295646;117396;93790;909621;2016-03-17
295646;117396;15714;898750;2016-03-17
295646;117396;73107;29211;2016-03-17
295646;117396;129720;1032305;2016-03-17
295646;117396;129720;1011780;2016-03-17
295646;117396;65789;1081925;2016-03-17
295646;117396;69199;969417;2016-03-17
295646;117396;6961;1019633;2016-03-17
....

```
请教下session-id是啥啊？
里面为啥好多NA啊，user-id是NA表示啥意思呢？
多谢大佬

**Comment by ucasiggcas** [comment]
ai, rensheng jiannan a

**Comment by ucasiggcas** [comment]
这里面的等于1为啥要去掉啊

```
# Filter out length 1 sessions
for s in list(sess_clicks):
    if len(sess_clicks[s]) == 1:
        del sess_clicks[s]
        del sess_date[s]
```

**Comment by ucasiggcas** [comment]
请教下timeframe是啥意思啊？
在一个session_id内按照timeframe对item_id排序是什么意思呢？咋不考虑eventdate呢？话说eventdate是什么呢？都是时间，一个具体一个不具体？？是这样吗？
多谢大佬

**Comment by 123malin** [comment]
> @123malin
> 大佬data_prepare.sh下载的数据如下示例：
> 
> ```
> session_id;user_id;item_id;timeframe;eventdate
> 1;NA;81766;526309;2016-05-09
> 1;NA;31331;1031018;2016-05-09
> 1;NA;32118;243569;2016-05-09
> 1;NA;9654;75848;2016-05-09
> 1;NA;32627;1112408;2016-05-09
> 1;NA;33043;173912;2016-05-09
> 1;NA;12352;329870;2016-05-09
> 1;NA;35077;390072;2016-05-09
> 1;NA;36118;487369;2016-05-09
> 1;NA;129055;991416;2016-05-09
> 2;NA;3147;883039;2016-05-09
> 2;NA;32754;359839;2016-05-09
> 2;NA;100747;38317;2016-05-09
> 2;NA;32971;182759;2016-05-09
> 2;NA;10657;387340;2016-05-09
> 2;NA;35606;756335;2016-05-09
> 2;NA;35606;53684;2016-05-09
> 2;NA;36246;332000;2016-05-09
> 2;NA;36246;722492;2016-05-09
> 2;NA;196110;1045018;2016-05-09
> 4;NA;13931;21812;2016-05-09
> 5;NA;5140;22430;2016-05-09
> 5;NA;35472;121036;2016-05-09
> 6;NA;73191;53123;2016-05-09
> 6;NA;382683;88337;2016-05-09
> 7;NA;59248;38806;2016-05-09
> 7;NA;59248;328086;2016-05-09
> 7;NA;9416;271202;2016-05-09
> 7;NA;40639;14808;2016-05-09
> 7;NA;40639;432980;2016-05-09
> 7;NA;40639;161072;2016-05-09
> 7;NA;73816;69100;2016-05-09
> 7;NA;32742;186920;2016-05-09
> 7;NA;79626;358743;2016-05-09
> 7;NA;388131;583388;2016-05-09
> 8;NA;11542;10067;2016-04-10
> 10;NA;69597;193275;2016-04-05
> 10;NA;5103;5639;2016-04-05
> .....
> 295645;NA;32950;263151;2016-03-22
> 295645;NA;68708;381295;2016-03-22
> 295645;NA;7017;22863;2016-03-22
> 295646;117396;20717;371823;2016-03-17
> 295646;117396;15330;822956;2016-03-17
> 295646;117396;30605;342923;2016-03-17
> 295646;117396;93790;909621;2016-03-17
> 295646;117396;15714;898750;2016-03-17
> 295646;117396;73107;29211;2016-03-17
> 295646;117396;129720;1032305;2016-03-17
> 295646;117396;129720;1011780;2016-03-17
> 295646;117396;65789;1081925;2016-03-17
> 295646;117396;69199;969417;2016-03-17
> 295646;117396;6961;1019633;2016-03-17
> ....
> ```
> 
> 请教下session-id是啥啊？
> 里面为啥好多NA啊，user-id是NA表示啥意思呢？
> 多谢大佬

session可以理解为一个浏览器session概念，创建一个网页会分配一个session。比如用户打开一个网页，点击了一系列物品，这整个过程都对应同一个session_id
user_id 为NA 应该是这个这个模型/数据集不需要用户用户信息

**Comment by 123malin** [comment]
> 这里面的等于1为啥要去掉啊
> 
> ```
> # Filter out length 1 sessions
> for s in list(sess_clicks):
>     if len(sess_clicks[s]) == 1:
>         del sess_clicks[s]
>         del sess_date[s]
> ```

这是个序列预测问题，长度为1的序列没有训练意义，就过滤掉了

**Comment by seiriosPlus** [comment]
此问题暂时没有收到有效的回复， 会close， 如有需要可reopen或重开issue.
