### ISSUE TITLE
NameError: name 'reduce' is not defined

### ISSUE THREAD

**Issue by YangYangL** [PaddlePaddle/PaddleRec#30]
官方代码 clone 下来，安装好后跑python -m paddlerec.run -m paddlerec.models.rank.dnn 报错；
NameError: name 'reduce' is not defined

**Comment by seiriosPlus** [comment]
请提供一下 Python 版本

**Comment by YangYangL** [comment]
> 请提供一下 Python 版本

python 3.7

**Comment by seiriosPlus** [comment]
我们复现一下， 会很快修复， 感谢.
