### ISSUE TITLE
DSSM模型实现有问题

### ISSUE THREAD

**Issue by v-mipeng** [PaddlePaddle/PaddleRec#451]
针对models/match/dssm目录下实现的DSSM模型我们发现以下几个问题：

1. 在net.py中，DSSM对于给定query的positive document和negative document使用了两个不同的编码器（self._pos_layers, self._neg_layers），这是不对的，所有的documents应该使用同一个编码器。
这一问题会导致所有pairs的预测similarity都很高。在修改这个问题之后，我们得到了91.38的正序率，远高于项目中报告的79的正序率。

2. 根据dygrapy_model.py中的loss定义函数定义，模型将最大化所有net.py返回的hit_prob的值（概率）。 目前，因为实验中只选择了一个negative样本且使用了slice函数进行切片, 所以对当前实验没有问题。但是如果negative样本数目大于1的话，hit_prob中将会返回negative样本的预测概率，导致模型最大化negative样本的预测概率。为了保证模型的适用性，建议将net.py中的slice切片实现修改为：hit_prob = paddle.slice( prob, axes=[0, 1], starts=[0, 0], ends=[self.slice_end, 1]) 。

另外提一个改进建议，在cosine similarity 的基础上做softmax是不合适的，因为cosine similarity的值域为[-1, 1], 在此基础上做softmax, 正样本的概率最大为：exp(1)/(exp(1) +  N_n exp(-1)), 其中N_n为negative样本数目，会导致较大的损失。应该直接把内积输入到softmax层，这一做法可以进一步将上面的91.38提高到93.96.

**Comment by yinhaofeng** [comment]
感谢反馈，已修复相关问题：https://github.com/PaddlePaddle/PaddleRec/pull/464
