### ISSUE TITLE
Wide&Deep代码中对所有sparse特征只用一个embedding

### ISSUE THREAD

**Issue by lhbrichard** [PaddlePaddle/PaddleRec#470]
wide deep代码里对sparse特征先做embedding，查看代码发现是直接统计所有sparse特征取值不同的数值，作为sparse_feature_number，来初始化一个embedding layer的，那这样子做岂不是不同sparse feature有同个值，embedding后的结果是一样的，比如A字段也有数值2，B字段也有数值2，这样子是不是没有区分度了
![image](https://user-images.githubusercontent.com/33123730/123033875-12d3ad80-d41b-11eb-9504-b4d2a88ded46.png)
![image](https://user-images.githubusercontent.com/33123730/123033895-1f580600-d41b-11eb-9be5-7f9897dab527.png)

**Comment by frankwhzhang** [comment]
需要自己对多个特征值进行id的区分

**Comment by lhbrichard** [comment]
看来可以用一个字典来做 好的了解了 谢谢～
