### ISSUE TITLE
Convert mind model met the problem

### ISSUE THREAD

**Issue by linWujl** [PaddlePaddle/PaddleRec#552]
Hi, when i used paddle_serving_client to convert the trained model, met the error, how can i fix the problem.

The two methods give the same result.

`python3 -m paddle_serving_client.convert --dirname model --model_filename model/rec_static.pdmodel --params_filename model/rec_static.pdparams

import paddle_serving_client.io as serving_io
serving_io.inference_model_to_serving('model', serving_server="serving_server", serving_client="serving_client",  model_filename='model/rec_static.pdmodel', params_filename='model/rec_static.pdparams')`

InvalidArgumentError: Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 2459239552 found).
      [Hint: Expected version == 0U, but received version:2459239552 != 0U:0.] (at /paddle/paddle/fluid/framework/lod_tensor.cc:329)
      [operator < load_combine > error]

**Comment by bjjwwang** [comment]
```
python3 -m paddle_serving_client.convert --dirname model --model_filename rec_static.pdmodel --params_filename rec_static.pdparams
```
指定过一次dirname，后面直接指定文件名就可以了。
按照上面的来就可以

**Comment by frankwhzhang** [comment]
问题已解决 暂时关闭issue
