### ISSUE TITLE
剩下的只有paddle1.8的模型有计划时间升级到2.1版本吗？

### ISSUE THREAD

**Issue by JoshonSmith** [PaddlePaddle/PaddleRec#561]
剩下的paddle1.8的模型有计划时间升级到2.1版本吗？
比如 Deep crossing， DCN， DIN， DIEN等等

**Comment by yinhaofeng** [comment]
您可以尝试切换到master分支，目前我们在master分支中已经升级了DCN， DIN， DIEN模型。
