### ISSUE TITLE
fm net.py部分bug

### ISSUE THREAD

**Issue by tz28** [PaddlePaddle/PaddleRec#570]
https://github.com/PaddlePaddle/PaddleRec/blob/bcddcf46e5cd8d4e6b2c5ee8d0d5521e292a2a81/models/rank/fm/net.py#L40
fm模型这个地方代码是不是写错了？应该是self.fm.forward(sparse_inputs, dense_inputs)吧

**Comment by tz28** [comment]
https://github.com/PaddlePaddle/PaddleRec/blob/release/2.1.0/models/rank/fm/static_model.py#L72  这个地方同样的bug

**Comment by frankwhzhang** [comment]
感谢您的讨论，我们已安排相关同学跟进
