### ISSUE TITLE
使用排序模型xdeepfm，如何得到数据之间的前后顺序？

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleRec#589]
目前infer.py没有做相关的输出

**Comment by yinhaofeng** [comment]
输入顺序即输出顺序

**Comment by zouhan6806504** [comment]
> 输入顺序即输出顺序

不是这个意思，我说的是比如我从召回模型得出了前50，然后训练了个xdeepfm给这50个item排序，如何确定这50个item的顺序（用户最有可能点击的排在前面）。我目前改了下models\rank\xdeepfm下dygraph_model.py，将infer_forward(self, dy_model, metrics_list, batch_data, config)中pred = dy_model.forward(sparse_tensor, dense_tensor)这个概率输出作为排序依据，这么做没问题吧？

**Comment by yinhaofeng** [comment]
没问题
