### ISSUE TITLE
mind的eval阶段，数据读取会droplast，导致预测的数据会少一部分

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleRec#595]

**Comment by zouhan6806504** [comment]
直接将droplast写成False也不起效

**Comment by zouhan6806504** [comment]
最后修改inferbatchsize为1才行

**Comment by yinhaofeng** [comment]
尝试修改PaddleRec/tools/utils/utils_single.py中def create_data_loader函数的倒数第二行。将dataloader这个api的参数drop_last改为False。如果没有生效可能是paddle版本问题，需要将paddle版本更换为最新的2.2或者develop即可生效

**Comment by zouhan6806504** [comment]
> 尝试修改PaddleRec/tools/utils/utils_single.py中def create_data_loader函数的倒数第二行。将dataloader这个api的参数drop_last改为False。如果没有生效可能是paddle版本问题，需要将paddle版本更换为最新的2.2或者develop即可生效

是paddle版本的问题，改成2.2就行了
