### ISSUE TITLE
PaddleRec/core/trainers/single_trainer.py中cudaplace设置不灵活

### ISSUE THREAD

**Issue by gentelyang** [PaddlePaddle/PaddleRec#63]
device = envs.get_global_env("device")
        if device == 'gpu':
            self._place = fluid.CUDAPlace(0)
        elif device == 'cpu':
            self._place = fluid.CPUPlace()

**Comment by MrChengmo** [comment]
已经伴随Trainer 重构完成了修复

https://github.com/PaddlePaddle/PaddleRec/pull/54
