### ISSUE TITLE
在运行paddle_infer.py时发现auto_log模块缺失

### ISSUE THREAD

**Issue by gouzil** [PaddlePaddle/PaddleRec#643]
![截屏2021-12-14 上午12 08 58](https://user-images.githubusercontent.com/66515297/145847049-04dfc172-eb67-4b2c-951d-1a56805ffe43.png)

**Comment by yinhaofeng** [comment]
auto_log的安装方法：https://github.com/PaddlePaddle/PaddleRec/blob/master/test_tipc/doc/test_train_inference_python.md

**Comment by gouzil** [comment]
ok解决了，谢了
