### ISSUE TITLE
代码规范性问题

### ISSUE THREAD

**Issue by tz28** [PaddlePaddle/PaddleRec#693]
dcn模型中，链接：https://github.com/PaddlePaddle/PaddleRec/blob/master/models/rank/dcn/net.py#L73，
请把注释掉的代码清理，因为这个无关代码中shape=[100004]就是个错的，极易误导人，让人以为layer_w的shape为100004。实际上layer_w的shape为13+26*9。如果这段代码不用了请删除，更别提是错的带有误导性的注释代码，更应该删除。

**Comment by yinhaofeng** [comment]
感谢您的反馈，我们会清理相关注释代码
