### ISSUE TITLE
DIEN组网代码一点疑惑

### ISSUE THREAD

**Issue by tz28** [PaddlePaddle/PaddleRec#713]
DIEN组网代码中，下面这两行调用的add_sublayer()函数【self.add_sublayer('linear_%d' % i, linear)】，在传入的name都是'linear_%d' % i的情况下，是否会后面即L144里的覆盖L123里的，如果会覆盖，这么操作两遍add_sublayer()的目的是什么？
https://github.com/PaddlePaddle/PaddleRec/blob/master/models/rank/dien/net.py#L123
https://github.com/PaddlePaddle/PaddleRec/blob/master/models/rank/dien/net.py#L144

**Comment by wangzhen38** [comment]
两个名字不该重复的，我们会尽快修改，感谢反馈～

**Comment by tz28** [comment]
> 两个名字不该重复的，我们会尽快修改，感谢反馈～

好的，点赞

**Comment by tz28** [comment]
> 两个名字不该重复的，我们会尽快修改，感谢反馈～

另外，还有个问题，在实现dien论文中的辅助loss即aux_loss（论文中的公式6）时，漏了下面公式中的 1-
![image](https://user-images.githubusercontent.com/9672354/155499151-2372787f-299d-44d1-b3fd-99616465fa00.png)

代码链接：https://github.com/PaddlePaddle/PaddleRec/blob/master/models/rank/dien/net.py#L243
