### ISSUE TITLE
预测结果数据的输出在哪里？

### ISSUE THREAD

**Issue by veridone** [PaddlePaddle/PaddleRec#735]
按照 https://github.com/PaddlePaddle/PaddleRec/blob/master/tools/readme.md
python -u tools/static_infer.py -m models/rank/dnn/config.yaml
这个预测的是 test目录下的数据，但是输出在哪里目录？
看来原代码里主要是AUC的数据，没有具体每行数据的预测结果

**Comment by yinhaofeng** [comment]
这里为了显示简洁，没有显示具体每条数据的输出，如果有需要可以将batch_size调整为1，print_interval也调整为1，即显示每一条数据了

**Comment by veridone** [comment]
这个fetch_batch_var就是预测的结果？            
fetch_batch_var = exe.run(
                program=paddle.static.default_main_program(),
                feed=dict(zip(input_data_names, batch_data)),
                fetch_list=[var for _, var in fetch_vars.items()])

**Comment by yinhaofeng** [comment]
这里是输出fetch_list的预测结果，如果您在fetch_list中指定的事预测值即为预测结果
