### ISSUE TITLE
静态图训练时，每个epoch之后，内存累加

### ISSUE THREAD

**Issue by JingyibySUTsoftware** [PaddlePaddle/PaddleRec#746]
静态图训练时，每个epoch训练完成使用save_interface接口保存模型，内存会增加一些，导致无法进行多轮训练

**Comment by wangzhen38** [comment]
你好，请提供下详细的运行环境及问题描述，我这边先复现下

**Comment by JingyibySUTsoftware** [comment]
> 你好，请提供下详细的运行环境及问题描述，我这边先复现下

在BML Codelab上运行项目，使用PaddleRec静态图训练一个模型
!cd ./PaddleRec/models/demo/shop && python -u ../../tools/static_trainer.py -m rank/config.yaml

config.yaml配置
  epochs: 10
  use_inference: True
使用save_interface接口保存模型，但是只能训练8个epoch，因为第8个epoch中后内存就会不足，训练终止。

**Comment by wangzhen38** [comment]
请问用的哪个分支，master分支上没有./PaddleRec/models/demo/shop这个目录，只有一个movie_recommand目录，我在该目录下跑了static_trainer.py脚本，对应的rank，并没有复现该问题，可以正常跑完十个epoch。

**Comment by JingyibySUTsoftware** [comment]
> 请问用的哪个分支，master分支上没有./PaddleRec/models/demo/shop这个目录，只有一个movie_recommand目录，我在该目录下跑了static_trainer.py脚本，对应的rank，并没有复现该问题，可以正常跑完十个epoch。

您好，./PaddleRec/models/demo/shop目录是我的自建的实验目录，抱歉没有说明。但是我在使用官方的demo训练时，也会存在每个epoch之后内存增长现象，如图所示官方demo在epoch1和epoch2训练完成后内存状况。然而，官方demo的数据量比较小这种情况并不明显，当我使用千万级规模的数据训练相同网络时，每个epoch后内存增长量大约在3GB左右。这种情况下只能训练大约6个epoch
![_(3`RVAX5TH%G MKS@N$LMO](https://user-images.githubusercontent.com/51908047/166080889-1e29d6a9-e477-4ea7-b635-f58cd3f35c76.png)
![V)99K3 NYO)@SLZK Q_%N N](https://user-images.githubusercontent.com/51908047/166080920-e94dbea2-7e3a-4c97-a6ce-6fec81bb3c88.png)

**Comment by JingyibySUTsoftware** [comment]
检测之后这个问题是由于我的向量维度设置的比较大导致的
