### ISSUE TITLE
关于wide_deep model 的 TIPC 测试。

### ISSUE THREAD

**Issue by Li-fAngyU** [PaddlePaddle/PaddleRec#754]
你好我在fork项目后按照test_tipc里的readme.md文件里的指示进行测试。执行一下两条代码：
1.bash test_tipc/prepare.sh ./test_tipc/configs/wide_deep/train_infer_python.txt 'lite_train_lite_infer'
2.bash test_tipc/test_train_inference_python.sh ./test_tipc/configs/wide_deep/train_infer_python.txt 'lite_train_lite_infer'
再enable_tensorRT=True的情况下，测试失败，错误报告如下：
W0504 20:43:30.999462  1664 analysis_predictor.cc:795] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I0504 20:43:31.013504  1664 analysis_predictor.cc:576] TensorRT subgraph engine is enabled
[1m[35m--- Running analysis [ir_graph_build_pass][0m
[1m[35m--- Running analysis [ir_graph_clean_pass][0m
[1m[35m--- Running analysis [ir_analysis_pass][0m
Traceback (most recent call last):
  File "tools/paddle_infer.py", line 169, in <module>
    main(args)
  File "tools/paddle_infer.py", line 115, in main
    predictor, pred_config = init_predictor(args)
  File "tools/paddle_infer.py", line 93, in init_predictor
    predictor = create_predictor(config)
ValueError: (InvalidArgument) Pass tensorrt_subgraph_pass has not been registered. Please use the paddle inference library compiled with tensorrt or disable the tensorrt engine in inference configuration! 
  [Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/pass.h:236)

运行环境是AI Studio经典版  V100 32GB。
请问是因为环境的问题吗？

**Comment by Li-fAngyU** [comment]
@wangzhen38 你好我安装了带有trt编译的paddle(linux-cuda10.1-cudnn7.6-trt6-gcc8.2 python3.7)，然后也安装了tensorrt，可以成功import。但是还是会提示找不到tensorrt的动态库。
![image](https://user-images.githubusercontent.com/56572498/167050940-8d993277-e1e3-4c14-9bad-682e587636df.png)

**Comment by wangzhen38** [comment]
> @wangzhen38 你好我安装了带有trt编译的paddle(linux-cuda10.1-cudnn7.6-trt6-gcc8.2 python3.7)，然后也安装了tensorrt，可以成功import。但是还是会提示找不到tensorrt的动态库。 ![image](https://user-images.githubusercontent.com/56572498/167050940-8d993277-e1e3-4c14-9bad-682e587636df.png) 然后TIPC测试的时候，错误报告：
> 
> ```
> File "tools/paddle_infer.py", line 93, in init_predictor
>     predictor = create_predictor(config)
> RuntimeError: (Unavailable) Load tensorrt api getInferLibVersion failed
>   [Hint: p_getInferLibVersion should not be null.] (at /paddle/paddle/fluid/platform/dynload/tensorrt.h:114)
> ```

python3.7的环境，建议安装下最新的版本试下（https://paddle-inference-lib.bj.bcebos.com/2.3.0-rc0/python/Linux/GPU/x86-64_gcc8.2_avx_mkl_cuda11.2_cudnn8.2.1_trt8.0.3.4/paddlepaddle_gpu-2.3.0rc0.post112-cp37-cp37m-linux_x86_64.whl）另外，应该不需要额外单独安装tensorRT了

**Comment by Li-fAngyU** [comment]
谢谢你，我发现是需要额外单独安装TensorRT的，之前在设置路径的时候没有设置好，按照[URL](https://blog.csdn.net/qq_33047753/article/details/101604686)这里设置好环境变量后，就成功了，然后TIPC测试也成功run了。
