### ISSUE TITLE
grpc远程调用错误

### ISSUE THREAD

**Issue by wjy3326** [PaddlePaddle/PaddleRec#793]
在https://github.com/PaddlePaddle/PaddleRec/tree/master/recserving/movie_recommender 的test_client.py启动客户端过程中出现错误：
(image_text_match_tf_1.15) [user@tianhu-worker-5 movie_recommender]$ python test_client.py as 5
Traceback (most recent call last):
  File "test_client.py", line 81, in <module>
    print(get_as(req))
  File "test_client.py", line 66, in get_as
    response = stub.as_call(request)
  File "/home/user/anaconda3/envs/image_text_match_tf_1.15/lib/python3.6/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/user/anaconda3/envs/image_text_match_tf_1.15/lib/python3.6/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: Error 111 connecting to 172.17.0.1:6389. Connection refused."
        debug_error_string = "{"created":"@1654828488.731180301","description":"Error received from peer ipv4:127.0.0.1:8910","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Exception calling application: Error 111 connecting to 172.17.0.1:6389. Connection refused.","grpc_status":2}"
>"
        debug_error_string = "{"created":"@1654828488.732741464","description":"Error received from peer ipv4:192.168.10.87:8930","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Exception calling application: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNKNOWN\n\tdetails = "Exception calling application: Error 111 connecting to 172.17.0.1:6389. Connection refused."\n\tdebug_error_string = "{"created":"@1654828488.731180301","description":"Error received from peer ipv4:127.0.0.1:8910","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Exception calling application: Error 111 connecting to 172.17.0.1:6389. Connection refused.","grpc_status":2}"\n>","grpc_status":2}"
>
请问该怎么解决？

**Comment by LYuanLing** [comment]
请问你解决了吗 我也出现了这个问题

**Comment by husheng-liu** [comment]
改成这个： self.redis_cli = redis.StrictRedis(host="127.0.0.1", port="6379") 就可以
