### ISSUE TITLE
如何自定义优化器？

### ISSUE THREAD

**Issue by Waterkin** [PaddlePaddle/PaddleRec#837]
如题，如果想对已有模型如Shared-Bottom自定义优化器该怎么做呢？

**Comment by wangzhen38** [comment]
你可以参考下官网的API，但是不建议自己定义优化器，开发难度较大，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/Adam_cn.html#adam

**Comment by Waterkin** [comment]
> 你可以参考下官网的API，但是不建议自己定义优化器，开发难度较大，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/Adam_cn.html#adam

好的，谢谢
