### ISSUE TITLE
UnboundLocalError: local variable 'tensor_print_dict' referenced before assignment

### ISSUE THREAD

**Issue by wcode-wzx** [PaddlePaddle/PaddleRec#847]
infer.py 推理的时候，测试数据不够一个batch的时候，报错。

**Comment by wangzhen38** [comment]
请问是跑哪个模型时报的错呢

**Comment by wcode-wzx** [comment]
demo 里的双塔模型
PaddleRec/models/demo/movie_recommand/infer.py 
执行python -u infer.py -m recall/config.yaml 推理的时候，当测试数据不够一个batch 的时候会报错；
或者有很多数据，但最后一个batch，不够一个batch_size 的时候，末尾的数据会被舍去。

**Comment by wangzhen38** [comment]
> 

目前是这样的，可以先把batch size设置小一点～
