### ISSUE TITLE
GPU Training Issue

### ISSUE THREAD

**Issue by hqsiswiliam** [PaddlePaddle/PaddleRec#871]
Hi,

We are now trying GPU training on PaddleRec for [NCF example](https://paddlerec.readthedocs.io/en/latest/models/recall/ncf.html).

We enabled the GPU config in the `config.yaml` as: `use_gpu: True`

However, If we turn on this config, we get an error as follows:
```
RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/fluid/platform/download/cudnn.cc:59)
```
We installed CUDNN & CUDA via Ananconda like:
```
cudatoolkit               11.2.2              hbe64b41_10    conda-forge
cudnn                     8.2.1.32             h86fa8c9_0    conda-forge
```
But it doesn't work with it.

Here is the paddlepaddle we used in the example:
```
paddlepaddle-gpu          2.2.2                    pypi_0    pypi
```

**Comment by wangzhen38** [comment]
You can refer to this solution：https://blog.csdn.net/qq451882471/article/details/106967942
