### ISSUE TITLE
Implement Fastformer in the rank models for the experiments on MIND dataset

### ISSUE THREAD

**Issue by vic4code** [PaddlePaddle/PaddleRec#962]
I referred to this [repository](https://github.com/wuch15/Fastformer) by the author of Fastformer, which was proposed in 2021, and reimplemented it in the PaddlePaddle framework. The exact layers were not officially implemented by the author, only the core of Fastformer attention was revealed. I inherited the architecture of NAML and replaced the attention layers with Fastformer. The final AUC score can almost reach the state-of-the-art (SOTA) performance, even without powerful language models like UniLM, MOKA, or word embeddings from GPT. The AUC score on the test dataset after training for 9 epochs is 0.729. Although there are still some tasks to complete, I aim to contribute the core Fastformer attention models to PaddleRec first. Here is a screenshot of the results:

![Screenshot 2023-12-18 at 10 59 08 PM](https://github.com/PaddlePaddle/PaddleRec/assets/45786393/7735e2e7-4b6b-4ca4-b706-a841d44806e3)

## To-do
- Add metrics such as MRR, nDCG@5, nDCG@10 for evaluation.
- Integrate strong word embedding features from pretrained language models like UniLM, MOKA,...
- Make sure it works in the static modeling mode

**Comment by danleifeng** [comment]
Thanks for contributing! It is very helpful for other users!
